default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: busapp_development

test:
  <<: *default
  database: busapp_test

production:
  <<: *default
  database: busapp_production
  username: busapp 
  password: <%= ENV['ZULU-RAILS_DATABASE_PASSWORD'] %>
